# docker-compose.yml
version: '3'
services:
  pythonapp:
    image: todoapp:2.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - ENGINE=mysql.connector.django
      - NAME=app_db
      - USER=app_user
      - PASSWORD=1234
      - HOST=my-sqllocal
      - PORT=3306
    networks:
      - todoapp-net
    depends_on:
      mysqllocal:
        condition: service_started
    restart: unless-stopped
  mysqllocal:
    image: mysqllocal:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sqllocal
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=1234
    networks:
      - todoapp-net
networks:
  todoapp-net:
volumes:
  todoapp-db-data:
